languageCode = "en-us"
title = "Open Mapping for SDGs"
theme = "book"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    BookRepo = "https://github.com/hotosm/gpsdd-documentation"
    BookShowToC = false
    BookEditPath = "/edit/master/content/"

[imaging]
    resampleFilter = "box"
    quality = 75
